name = "ParticleProduction"
uuid = "9bf43886-47a1-4200-8895-38046e749360"
authors = ["nondairyneutrino <nathaniel.chapman@cwu.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
